### ISSUE TITLE
Invalid native has been passed

### ISSUE THREAD

**Issue by plusman1560mami** [Sighmir/YARP#17]
![Adsız](https://user-images.githubusercontent.com/50716802/57879857-f7674300-784f-11e9-9035-221614d617e4.png)
can you help me get an error like a guess the problem password

**Comment by Sighmir** [comment]
I searched on the whole project and theres nowhere where I call that native. 
That problem must be related to another script on your server.

**Comment by plusman1560mami** [comment]
I'm using your files , I didn't add anything else ,  can you look at the remote server, I've been trying every day for 2 months I'm even ready to pay

**Comment by Sighmir** [comment]
As you can see on the screenshot below:
![image](https://user-images.githubusercontent.com/7741292/58032666-7af78d00-7af9-11e9-835a-621c31a2e263.png)

The pattern on the begining of that message is not found in any file on my YARP repository folder that I just cloned.
The fix for that issue would be to replace the existing invalid native with it's valid hash, but since that hash doesn't exist in any file it's impossible for me to replace it for it's valid one.

A hash equivalent to that one that calls the same function is found on:
```
./YARP/client_packages/YARP/events/yarp/gamemode.js:18:  mp.game.invoke('0x95C0A5BBDC189AA1');
```
IF for some reason RAGE.MP is mapping this to the old native 0x0E09906A20E6D76F you need to replace it for the new one: 0x5D0FA97F2E6E2EB4

Unless one of the quick-updates changed the mapping for natives on RAGE.MP or a GTA V update made the old mapping invalid, I don't see how this could happen.

**Comment by plusman1560mami** [comment]
can not cancel this password ? there is no solution

**Comment by plusman1560mami** [comment]
let me take a look at the password ?

**Comment by Sighmir** [comment]
Take a look at what password ? There is no password.

My last message gives detailed explanation of why this is happening and how it can be solved.

**Comment by plusman1560mami** [comment]
Sorry, I failed my server ip :  185.171.90.14  username : web    password :
net147147..   please just help once

Guilherme Caulada <notifications@github.com>, 21 May 2019 Sal, 00:50
tarihinde şunu yazdı:

**Comment by plusman1560mami** [comment]
I sent you an email

**Comment by plusman1560mami** [comment]
if its possible can you please login my server for fixing this problem for that i can share my server details (ip-password etc.) with you , i spend a lot of time on it but i couldnt succeed and in my country i couldnt find a person who can help me

**Comment by Sighmir** [comment]
plusman1560mami your messages were deleted because they disclosed sensitive information as your **USERNAME** and **PASSWORD** as  well as your server **ADDRESS**, you are publicly disclosing information that could give ANYONE full access to your server machine!!! If you weren't hacked up to this point please consider changing the password for your machine or using a private key file. 

**NEVER** disclose your USERNAME and PASSWORD for **ANYTHING** much less your private server.

**Comment by plusman1560mami** [comment]
can you give me a discord

**Comment by Sighmir** [comment]
My Discord is on my GitHub profile as my Status - Sighmir#1621

**Comment by Sighmir** [comment]
This issue is related to https://github.com/MarcosRenato266/deft-server and not YARP.
