### ISSUE TITLE
Labels em Multiplayer dão erro.

### ISSUE THREAD

**Issue by MarcosRenato266** [Sighmir/YARP#3]
Aparentemente o for no tick do server está incorreto.

**Comment by Sighmir** [comment]
You were right.. I think indexing by the social club is better, but not only for the label, for all ticks, so I removed the argument id from the callback function and declared it as player.socialClub inside of it. 
This way its valid for all objects ticks, including players.
I also added some try...catch to the tick function so next time you will see where the issue is.

**Comment by Sighmir** [comment]
Please next time try to use the [issues template](https://raw.githubusercontent.com/Sighmir/YARP/master/ISSUE_TEMPLATE.md). 
This way I will have all information necessary to understand your issue/request.
So please don't delete the issue template, it's supposed to be answered to so the community can have all the information documented.
